name: ci

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max-old-space-size=6144
  NUXT_SITE_URL: https://example.com

permissions: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Type check
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint
      - name: Unit test
        run: pnpm run test:unit
      - name: Build
        run: pnpm run generate

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2
